Remove deploy workflow

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -124,18 +124,11 @@ jobs:
           name: setup
           path: build/Ninja-*.exe
 
-  deploy:
+  draft_release:
     runs-on: ubuntu-latest
     needs: setup
     if: startsWith(github.ref, 'refs/tags/')
     steps:
-      - name: Fetch build results
-        uses: actions/cache/restore@v4
-        with:
-          enableCrossOsArchive: true
-          fail-on-cache-miss: true
-          path: build
-          key: results-${{ github.run_id }}-${{ github.run_attempt }}
       - name: Draft release
         if: startsWith(github.ref, 'refs/tags/')
         run: |
@@ -145,46 +138,13 @@ jobs:
           echo "VERSION=${tag/v/}" >> $GITHUB_ENV
           echo "CHANGELOGID=${changelogid}" >> $GITHUB_ENV
           notes="<!-- <div align=\"center\"><table width=\"100%\"><td><b>&#x26A0; &nbsp; This version is outdated. Please use the <a href=\"https://github.com/szapp/Ninja/releases/latest\">lastest version</a> instead. &#x26A0; </b></td></table></div> -->"$'\n\n'"- [Change log](https://github.com/szapp/Ninja/wiki/Changelog#$changelogid)"$'\n'"- [Installation instructions](https://github.com/szapp/Ninja/wiki/Installation-(EN)#wiki-wrapper)"$'\n'"- [Check sums](https://github.com/szapp/Ninja/wiki/Checksums#wiki-wrapper)"$'\n\n'"<a href=\"https://ko-fi.com/szapp\"><img src=\"https://github.com/szapp/GothicFreeAim/assets/20203034/49fbc81a-69b2-4ee2-bfcb-eae746546894\" alt=\"\" height=\"12pt\" /></a>"
-          gh release create $tag -R ${{ github.repository }} -d --verify-tag --title "Ninja ${tag/v/}" --notes "$notes" build/Ninja-*.exe || echo "::error title=Release failed::Could not draft release for tag $tag"
+          gh release create $tag -R ${{ github.repository }} -d --verify-tag --title "Ninja ${tag/v/}" --notes "$notes" || echo "::error title=Release failed::Could not draft release for tag $tag"
         env:
           GITHUB_TOKEN: ${{ secrets.PAT }}
-      - name: Prepare Steam workshop upload
-        run: |
-          mkdir -p content/System
-          cp build/*.dll content/System/
-          curl -sLO https://github.com/user-attachments/files/15592985/BugslayerUtilG.zip
-          unzip BugslayerUtilG.zip -d content/System/
-          rm BugslayerUtilG.zip
-      - name: Update in Gothic 1 Steam workshop
-        if: startsWith(github.ref, 'refs/tags/')
-        uses: m00nl1ght-dev/steam-workshop-deploy@v3
-        with:
-          username: ${{ secrets.STEAM_USERNAME }}
-          configVdf: ${{ secrets.STEAM_CONFIG_VDF }}
-          path: content
-          appId: 65540
-          publishedFileId: 2786936496
-          changeNote: |
-            Version ${{ env.VERSION }}
-
-            https://github.com/szapp/Ninja/wiki/Changelog#${{ env.CHANGELOGID }}
-      - name: Update in Gothic 2 Steam workshop
-        if: startsWith(github.ref, 'refs/tags/')
-        uses: m00nl1ght-dev/steam-workshop-deploy@v3
-        with:
-          username: ${{ secrets.STEAM_USERNAME }}
-          configVdf: ${{ secrets.STEAM_CONFIG_VDF }}
-          path: content
-          appId: 39510
-          publishedFileId: 2786910489
-          changeNote: |
-            Version ${{ env.VERSION }}
-
-            https://github.com/szapp/Ninja/wiki/Changelog#${{ env.CHANGELOGID }}
 
   cleanup:
     runs-on: ubuntu-latest
-    needs: deploy
+    needs: setup
     if: ${{ !cancelled() }}
     permissions:
       actions: write
