Move draft into release workflow

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -59,6 +59,8 @@ jobs:
           source metadata
           ver=$VBASE.$VMAJOR.$VMINOR
           tag=v$ver
+          echo "VERSION=$ver" >> $GITHUB_ENV
+          echo "TAG=$tag" >> $GITHUB_ENV
           tagexists=$(git tag | grep -oP "^${tag}$" | wc -l)
           if [ $tagexists -gt 0 ]; then
             echo "::error title=Invalid version::A tag with the version $tag already exists!"
@@ -74,3 +76,20 @@ jobs:
           git commit -m "Bump version number"
           git tag -a $tag -m "Version $ver"
           git push --follow-tags
+      - name: Draft release
+        run: |
+          tag=${{ env.TAG }}
+          changelogdate=$(date +"%b-%-d-%Y")
+          changelogid="${tag//./}-${changelogdate,,}"
+          notes="<!-- <div align=\"center\"><table width=\"100%\"><td><b>&#x26A0; &nbsp; This version is outdated. Please use the <a href=\"https://github.com/szapp/Ninja/releases/latest\">lastest version</a> instead. &#x26A0; </b></td></table></div> -->
+
+          <!-- Short description -->
+
+          🗒️ [Change log](https://github.com/szapp/Ninja/wiki/Changelog#$changelogid)
+          🖥️ [Installation instructions](https://github.com/szapp/Ninja/wiki/Installation-(EN)#wiki-wrapper)
+          #️⃣ [Check sums](https://github.com/szapp/Ninja/wiki/Checksums#wiki-wrapper) for verification.
+          &nbsp;<img src=\"https://github.com/szapp/GothicFreeAim/assets/20203034/49fbc81a-69b2-4ee2-bfcb-eae746546894\" alt=\"\" height=\"12pt\" />&nbsp;<a href=\"https://ko-fi.com/szapp\">Support the project</a> to ensure its journey continues!
+          "
+          gh release create $tag -R ${{ github.repository }} -d --verify-tag --title "Ninja ${{ env.VERSION }}" --notes "$notes" || echo "::error title=Release failed::Could not draft release for tag $tag"
+        env:
+          GITHUB_TOKEN: ${{ secrets.PAT }}
